django_project_boilerplate/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('gallery/', views.gallery, name='gallery'),
]

django_project_boilerplate/newstore/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django_project_boilerplate/core/models.py
from django.db import models


class Artwork(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='artwork_images')

django_project_boilerplate/core/views.py
from django.shortcuts import render
from .models import Artwork


def homepage(request):
    return render(request, 'homepage.html')


def gallery(request):
    artworks = Artwork.objects.all()
    context = {
        'artworks': artworks
    }
    return render(request, 'gallery.html', context)

django_project_boilerplate/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block content  %}
    {% endblock content %}
</body>
</html>

django_project_boilerplate/templates/contact.html
<div id="contact" class="section db">
    <div class="container">
        <div class="section-title text-center">
            <h3>Contact Me</h3>
            <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
        </div><!-- end title -->

        <div class="row">
            <div class="col-md-12">
                <div class="contact_form">
                    <div id="message"></div>
                    <form id="contactForm" name="sentMessage" novalidate="novalidate">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input class="form-control" id="name" type="text" placeholder="Your Name"
                                        required="required" data-validation-required-message="Please enter your name.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" id="email" type="email" placeholder="Your Email"
                                        required="required"
                                        data-validation-required-message="Please enter your email address.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" id="phone" type="tel" placeholder="Your Phone"
                                        required="required"
                                        data-validation-required-message="Please enter your phone number.">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <textarea class="form-control" id="message" placeholder="Your Message"
                                        required="required"
                                        data-validation-required-message="Please enter a message."></textarea>
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div>
                                <button id="sendMessageButton" class="sim-btn btn-hover-new" data-text="Send Message"
                                    type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end section -->

django_project_boilerplate/templates/gallery.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Art Gallery</h1>
    <div class="row">
        {% for artwork in artworks %}
        <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
            <div class="card">
                <img class="card-img-top" src="{{ artwork.image.url }}" alt="{{ artwork.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ artwork.title }}</h5>
                    <p class="card-text">{{ artwork.description }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

django_project_boilerplate/templates/homepage.html
<!DOCTYPE html>
<html lang="en">

<!-- Basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Site Metas -->
<title>Blooms Art Blog</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">

<!-- Site Icons -->
<link rel="shortcut icon" href="" type="image/x-icon" />
<link rel="apple-touch-icon" href="">

<!-- Bootstrap CSS -->

<!-- Site CSS -->
<style>
	.nav-bar {
		display: flex;
		justify-content: space-between;
		align-items: center;
		background-color: white;
		height: 50px;
		margin-bottom: 10px;
	}

	.nav-bar ul {
		list-style: none;
		margin: 0;
		padding: 0;
	}

	.nav-bar li {
		display: inline-block;
		margin-right: 10px;
		margin-left: 10px;
	}

	.nav-bar a {
		display: block;
		padding: 10px;
		color: lightskyblue;
		text-decoration: none;
	}

	.topnav-left {
		flex-grow: 1;
	}

	.topnav-right {
		text-align: right;
	}

	.main {
		margin-top: 5px;
	}

	.carousel {
		display: flex;
		justify-content: center;
		align-items: center;
		background: linear-gradient(to right, #FFC0CB, #FF69B4);
		padding: 20px;
		border-radius: 5px;
	}

	.carousel h2 {
		text-align: center;
		color: #fff;
	}

	.message-box {
		display: flex;
		justify-content: center;
		align-items: center;
		width: 80%;
		margin: 0 auto;
		border: 1px solid #ccc;
		border-radius: 5px;
		padding: 20px;
	}

	.message-box p {
		text-align: left;
		margin-right: 20px;
	}

	.message-box .card {
		width: 150px;
		height: 150px;
		border-radius: 5px;
		background-color: #ccc;
	}
</style>
<!-- Responsive CSS -->

<!-- Custom CSS -->

<!-- Modernizr -->

<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

	<div class="nav-bar">
		<div class="topnav-left">
			<ul>
				<li><a href="">Home</a></li>
				<li><a href="{% url 'core:gallery' %}">Gallery</a></li>
			</ul>
		</div>
		<div class="'topnav-right">
			<ul>
				<li><a href="">Service</a></li>
				<li><a href="">Contact</a></li>
			</ul>
		</div>
	</div>

	<section id="home" class="main">
		<div class="carousel">
			<h2>Welcome to my blog</h2>
			<p></p>
		</div>
	</section>

	<div id="about" class="section wb">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<div class="message-box">
						<h2> Rocky Rosato </h2>
						<p> Integer rutrum ligula eu dignissim laoreet. Pellentesque venenatis nibh sed tellus
							faucibus
							bibendum. Sed fermentum est vitae rhoncus molestie. Cum sociis natoque penatibus et
							magnis
							dis parturient montes, nascetur ridiculus mus. Sed vitae rutrum neque. Ut id erat sit
							amet
							libero bibendum aliquam. Donec ac egestas libero, eu bibendum risus. Phasellus et congue
							justo. Integer rutrum ligula eu dignissim laoreet. Pellentesque venenatis nibh sed
							tellus
							faucibus bibendum. Sed fermentum est vitae rhoncus molestie. Cum sociis natoque
							penatibus et
							magnis dis parturient montes, nascetur ridiculus mus.</p>
						<p>Sed vitae rutrum neque. Ut id erat sit amet libero bibendum aliquam. Donec ac egestas
							libero,
							eu bibendum risus. Phasellus et congue justo.</p>

						<div class="col-md-6">
							<div class="card">
								<img src="" alt="image goes here" class="img-fluid img-rounded">
							</div><!-- end media -->
						</div><!-- end col -->
					</div><!-- end row -->
				</div><!-- end container -->
			</div><!-- end section -->

			<div class="copyrights">
				<div class="container">
					<div class="footer-distributed">
						<div class="footer-left">
							<p class="footer-links">
								<a href="#">Home</a>
								<a href="#">Blog</a>
								<a href="#">Faq</a>
								<a href="#">Contact</a>
							</p>
							<p class="footer-company-name">All Rights Reserved. &copy; 2018 <a href="#">Blog</a>
								Design
								By :
								<a href="https://html.design/">Nave</a>
							</p>
						</div>
					</div>
				</div><!-- end container -->
			</div><!-- end copyrights -->

			<a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-camera" aria-hidden="true"></i>
			</a>
		</div>
	</div>
</body>

</html>

django_project_boilerplate/templates/item_list.html
{% extends "base.html" %}

{% block content %}
<h2>Here are the list of items</h2>

{% for item in items %}
{{ item }}
{% endfor %}
{% endblock content %}

django_project_boilerplate/templates/services.html
<div id="services" class="section lb">
    <div class="container">
        <div class="section-title text-center">
            <h3>Services</h3>
            <p>Quisque eget nisl id nulla sagittis auctor quis id. Aliquam quis vehicula enim, non aliquam risus.</p>
        </div><!-- end title -->

        <div class="row">
            <div class="col-md-4">
                <div class="services-inner-box">
                    <div class="ser-icon">
                        <i class="flaticon-wedding-photo"></i>
                    </div>
                    <h2>Wedding Photography</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua.</p>
                </div>
            </div><!-- end col -->
            <div class="col-md-4">
                <div class="services-inner-box">
                    <div class="ser-icon">
                        <i class="flaticon-image"></i>
                    </div>
                    <h2>Portrait photography</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua.</p>
                </div>
            </div><!-- end col -->
            <div class="col-md-4">
                <div class="services-inner-box">
                    <div class="ser-icon">
                        <i class="flaticon-event"></i>
                    </div>
                    <h2>Event Photography</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua.</p>
                </div>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end section -->